import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    lang="en">
      <body className="min-h-full flex flex-col">
        <h1>NAVBAR</h1>
        {children}
        <h1>footer</h1>
        </body>
    </html>
  );
}
